server:
  port: 8081
spring:
  application:
    name: media-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/media?createDatabaseIfNotExist=true
    username: root
    password: ${media-db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

cloud:
  aws:
    region.static: ap-southeast-1
    credentials:
      accessKey: ${access-key}
      secretKey: ${secret-key}
    endpointUrl: https://s3.ap-southeast-1.amazonaws.com
    bucketName: uit-thesis-media-service


